# Generated by Django 6.0.3 on 2026-03-23 11:00

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The length of the post must be between 40 and 60 characters', max_length=60, validators=[django.core.validators.MinLengthValidator(40)])),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('reference_url', models.URLField(blank=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(default='post_images/algorithm1.jpeg', help_text='For bests results, use an image that is 1,200px wide x 600px high', max_length=200, upload_to='post_images')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], db_index=True, default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(help_text='Select more than one category by holding down Ctrl or Cmd key', related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-updated_date', '-publish_date'],
                'default_manager_name': 'objects',
            },
        ),
    ]
