# Generated by Django 6.0.3 on 2026-04-30 08:57

import apps.account.utils
import django.db.models.deletion
import django_otp.util
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author_view', models.IntegerField(choices=[(0, 'Username'), (1, 'Full Name')], default=0)),
                ('profile_picture', models.ImageField(default='profile_pics/default-user.jpg', max_length=200, upload_to='profile_pics')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_email_address', models.EmailField(max_length=254)),
                ('challenge_token', encrypted_model_fields.fields.EncryptedCharField(default=django_otp.util.random_hex, validators=[apps.account.utils.token_validator])),
                ('challenge_generation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('challenge_expiration_timestamp', models.DateTimeField(blank=True, default=apps.account.utils.get_challenge_expiration_timestamp, null=True)),
                ('challenge_completed', models.BooleanField(default=False)),
                ('challenge_completed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('token_expiration_timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
